// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./../../src/components/counter.vue')['default']
    'IAntDesign:minusOutlined': typeof import('~icons/ant-design/minus-outlined')['default']
    'IMdi:emoticonWinkOutline': typeof import('~icons/mdi/emoticon-wink-outline')['default']
    'IMdi:minus': typeof import('~icons/mdi/minus')['default']
    'IMdi:themeLightDark': typeof import('~icons/mdi/theme-light-dark')['default']
    'IOcticon:dot24': typeof import('~icons/octicon/dot24')['default']
    'IPh:numberCircleEightLight': typeof import('~icons/ph/number-circle-eight-light')['default']
    'IRi:addFill': typeof import('~icons/ri/add-fill')['default']
    'IUil:minus': typeof import('~icons/uil/minus')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoItem: typeof import('./../../src/components/todo/TodoItem.vue')['default']
  }
}
