// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./../../src/components/counter.vue')['default']
    'IIc:outlineDarkMode': typeof import('~icons/ic/outline-dark-mode')['default']
    'IIc:outlineLightMode': typeof import('~icons/ic/outline-light-mode')['default']
    'IIconoir:github': typeof import('~icons/iconoir/github')['default']
    'IIconoir:home': typeof import('~icons/iconoir/home')['default']
    'IMdi:alarmCheck': typeof import('~icons/mdi/alarm-check')['default']
    'IMdi:emoticonWinkOutline': typeof import('~icons/mdi/emoticon-wink-outline')['default']
    'IMdi:formatListBulleted': typeof import('~icons/mdi/format-list-bulleted')['default']
    'IMdi:minus': typeof import('~icons/mdi/minus')['default']
    'IPh:numberCircleEightLight': typeof import('~icons/ph/number-circle-eight-light')['default']
    'IRi:addFill': typeof import('~icons/ri/add-fill')['default']
    Nav: typeof import('./../../src/components/nav/Nav.vue')['default']
    PanLoader: typeof import('./../../src/components/panLoder/PanLoader.vue')['default']
    PanLoder: typeof import('./../../src/components/panLoder/index.vue')['default']
    ProgressView: typeof import('./../../src/components/ProgressView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../../src/components/sidebar/SideBar.vue')['default']
    TodoItem: typeof import('./../../src/components/todo/TodoItem.vue')['default']
  }
}
